---
title: "p8105_hw6_cl4043"
author: "Stella Li"
date: "12/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
library(purrr)
library(rvest)
```

## Problem 1

```{r message=FALSE, warning=FALSE}
homicide_df = read_csv("./data/homicide-data.csv", na = c("", "NA", "Unknown")) %>%
  mutate(city_state = str_c(city, state, sep = "_"), 
         victim_age = as.numeric(victim_age),
         resolved = case_when(
           disposition == "Closed without arrest" ~ 0,
           disposition == "Open/No arrest" ~ 0,
           disposition == "Closed by arrest" ~ 1,
           )) %>%
  filter(city_state != "Tulsa_AL") %>%
  filter(victim_race %in% c("White", "Black")) %>%
  select(city_state, resolved, victim_age, victim_race, victim_sex)
```


```{r message=FALSE, warning=FALSE}
# Generate a table of Confidence Intervals for the Odds Ratios
baltimore_df =
  homicide_df %>%
  filter(city_state == "Baltimore, MD")

glm(resolved ~ victim_age + victim_race + victim_sex, 
	    data= baltimore_df,
	    family = binomial()) %>%
  
  broom::tidy() %>%
  mutate(OR = exp(estimate),
         CI_lower = exp(estimate -1.96 * std.error),
         CI_upper = exp(estimate + 1.96 * std.error)) %>%
  select(term, OR, starts_with("CI")) %>%
  knitr::kable(digits = 3)
```

```{r message=FALSE, warning=FALSE}
# Fix data to then generate a plot of confidence intervals.
models_results_df = 
	  homicide_df %>%
	  nest(data = -city_state) %>%
	  mutate(
	    models = 
	      map(.x = data, ~glm(resolution ~ victim_age + victim_race + victim_sex, data = .x, family = binomial())),
	    results = map(models, broom::tidy) 
	  ) %>%
	    select(city_state, results) %>%
	  unnest(results) %>%
	  mutate(OR = exp(estimate),
	         CI_lower = exp(estimate -1.96 * std.error),
	         CI_upper = exp(estimate + 1.96 * std.error)) %>%
	  select(city_state, term, OR, starts_with("CI"))
```


```{r message=FALSE, warning=FALSE}
# Create a plot of Confidence Intervals
models_results_df %>%
  filter(term == "victim_sexMale") %>%
  mutate(city_state = fct_reorder(city_state, OR)) %>%
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) +
  theme(axis.text = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(
    title = "Confidence Intervals",
    x = "City and State",
    y = "Odds Ratio(OR)",
    caption = "Data from the Washington Post GitHub")
```

## Problem 2

```{r message=FALSE, warning=FALSE}
birthweight <- read_csv("./data/birthweight.csv", na = c("", "NA", "Unknown")) %>%
  janitor::clean_names() %>%
  mutate(babysex = as_factor(babysex),
         frace = as_factor(frace),
         malform = as_factor(malform),
         mrace = as_factor(mrace))
```

```{r message=FALSE, warning=FALSE}
# fitting a regression model to baby weight
full_model_bw <- lm(bwt ~ ., data = birthweight)
step(full_model_bw, direction='backward')
```

```{r message=FALSE, warning=FALSE}
# Compare the model generated from backward stepwise selection with the same model now including mother's race as a covariate
model_1 <- lm(bwt ~ babysex + bhead + blength + delwt + fincome + 
    gaweeks + mheight + parity + ppwt + smoken + momage, data = birthweight)
model_2 <- lm(bwt ~ babysex + bhead + blength + delwt + fincome + 
    gaweeks + mheight + parity + ppwt + smoken + momage + mrace, data = birthweight)
anova(model_1, model_2)
summary(model_1)
summary(model_2)
```

As we can see from the p-value, 2.2e-16, so we rejected the null hypothesis and conclude that the larger model is superior.

```{r message=FALSE, warning=FALSE}
# Choose the bigger model and plot the residuals vs fitted values.
birthweight %>% 
  modelr::add_residuals(model_2) %>%
  modelr::add_predictions(model_2) %>%
  ggplot(aes(x = pred, y = resid)) + geom_point() + 
  labs(
    title = "Residuals versus Fitted Values",
    x = "Fitted Values",
    y = "Residuals"
  )

birthweight %>% 
  modelr::add_residuals(model_2) %>%
  modelr::add_predictions(model_2) %>%
  ggplot(aes(x = resid)) + geom_density() + 
  labs(
    title = "Residuals versus Fitted Values",
    x = "Fitted Values",
    y = "Residuals"
  )
```
From the histogram, we can see that the residuals look almost normal.

```{r message=FALSE, warning=FALSE}
# One using length at birth and gestational age as predictors (main effects only)
# One using head circumference, length, sex, and all interactions (including the three-way interaction) between these
set.seed(1)
fit_1 = lm(bwt ~ blength + gaweeks, data = birthweight)
fit_2 = lm(bwt ~ bhead * blength * babysex, data = birthweight)

cv_df =
  crossv_mc(birthweight, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))

cv_df = 
  cv_df %>% 
  mutate(
    simple_model = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    interaction_model = map(train, ~lm(bwt ~ bhead * blength * babysex, data = .x)),
    full_model = map(train, ~lm(bwt ~ babysex + bhead + blength + delwt + fincome + 
    gaweeks + mheight + mrace + parity + ppwt + smoken + momage, data = birthweight))
  ) %>%
    
  mutate(
    rmse_simple = map2_dbl(simple_model, test, ~rmse(model = .x, data = .y)),
    rmse_interaction = map2_dbl(interaction_model, test, ~rmse(model = .x, data = .y)),
    rmse_full_model = map2_dbl(full_model, test, ~rmse(model = .x, data = .y))
    )

cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin() + 
  labs(
    title = "RMSE for Each of the Three Birthweight Models",
    x = "Model",
    y = "RMSE"
  )
```


## Problem 3

```{r message=FALSE, warning=FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


```{r message=FALSE, warning=FALSE}
# drawing bootstrap samples
set.seed(1)
boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}
boot_straps = 
  data_frame(
    strap_number = 1:5000,
    strap_sample = rerun(5000, boot_sample(weather_df))
  )
bootstrap_results = 
  boot_straps %>% 
  mutate(
    models = map(strap_sample, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::glance),  
    results_2 = map(models, broom::tidy)) %>%
  select(-strap_sample, -models) %>% 
  unnest(results,
         results_2) %>% 
  select(strap_number, r.squared, term, estimate) %>%
  pivot_wider(names_from = term,
              values_from = estimate) %>%
  janitor::clean_names() %>%
  mutate(log_value = log(intercept * tmin))

# plotting bootstrap results
bootstrap_results %>% 
  ggplot(aes(x = r_squared)) + 
  geom_density() + 
  labs(
    title = "5000 Boostrap Estimates of r^2",
    x = "r^2",
    y = "Density"
  )
bootstrap_results %>%
  ggplot(aes(x = log_value)) + 
  geom_density()
```
The distributions of both the R^2 values and the log(B_0_hat*B_1_hat) values seem to follow fairly normal distributions.  

```{r messages=FALSE, warning=FALSE}
# constructing confidence intervals
bootstrap_results %>% 
  summarize(
    ci_lower_rsqd = quantile(r_squared, 0.025), 
    ci_upper_rsqd = quantile(r_squared, 0.975),
    ci_lower_log = quantile(log_value, 0.025), 
    ci_upper_log = quantile(log_value, 0.975)) %>%
  rename(`R^2 Lower CI` = ci_lower_rsqd,
         `R^2 Upper CI` = ci_upper_rsqd,
         `log(B0hat*B1hat) Lower CI` = ci_lower_log,
         `log(B0hat*B1hat) Upper CI` = ci_upper_log)

```

